DROP TABLE IF EXISTS USER_TABLE CASCADE;

CREATE TABLE USER_TABLE (
    user_id INT GENERATED ALWAYS AS IDENTITY UNIQUE NOT NULL,
    username varchar(32) NOT NULl,
    password_hash varchar(60) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    nuked BOOL NOT NULL DEFAULT FALSE
);
