DROP TABLE IF EXISTS WORLD CASCADE;

CREATE TABLE WORLD (
  id INT GENERATED ALWAYS AS IDENTITY UNIQUE NOT NULL,
  user_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tiles JSONB NOT NULL DEFAULT '[]',
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at TIMESTAMP
);

DROP TABLE IF EXISTS ENTITY CASCADE;

CREATE TABLE ENTITY (
  id VARCHAR(32) NOT NULL UNIQUE PRIMARY KEY,
  world_id INT NOT NULL REFERENCES WORLD(id),
  template boolean NOT NULL DEFAULT FALSE,
  physics JSONB,
  graphics JSONB
);